name: Generate Stats Cards

on:
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hours
  workflow_dispatch:      # Allows manual trigger
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch Stats Cards
        run: |
          mkdir -p assets
          curl -s -o assets/stats.svg "https://github-stats-extended.vercel.app/api?username=Samy6767f&show_icons=true&theme=vibrant&locale=en"
          curl -s -o assets/langs.svg "https://github-stats-extended.vercel.app/api/top-langs/?username=Samy6767f&layout=compact&theme=vibrant"

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/*.svg
          if ! git diff --cached --quiet; then
            git commit -m "Update static stats cards"
            git push
          else
            echo "No changes to stats cards"
          fi
